export const interviewsData = [
  {
    id: 1,
    name: 'Mr. Shriram Ramanathan',
    title: 'Chief Investment Officer - FIXED INCOME',
    company: 'HSBC Mutual Fund',
    excerpt: 'CIO - Fixed Income, overseeing the management of about INR40,000cr (~USD 8bn), in assets across various Fixed income and Hybrid funds (INR only).',
    date: 'April 20, 2025',
    duration: '15 min',
    image: '/images/interviews/img1.jpg',
    slug: 'shriram-ramanathan',
    category: 'Fund Managers',
  },
  {
    id: 2,
    name: 'Mr. Venugopal Manghat',
    title: 'Chief Investment Officer - Equity',
    company: 'HSBC Mutual Fund',
    excerpt: 'Venugopal Manghat is the Chief Investment Officer (CIO) - Equity of HSBC Mutual Fund.',
    date: 'April 20, 2025',
    duration: '12 min',
    image: '/images/interviews/img2.jpg',
    slug: 'venugopal-manghat',
    category: 'Fund Managers',
  },
  {
    id: 3,
    name: 'Mr. Vikas Garg',
    title: 'Head - Fixed Income India',
    company: 'Invesco Mutual Fund',
    excerpt: 'Vikas heads the Fixed Income investment function at Invesco India and also serves as a fund manager for various duration-oriented debt schemes at Invesco India.',
    date: 'March 25, 2025',
    duration: '10 min',
    image: '/images/interviews/img3.jpg',
    slug: 'vikas-garg',
    category: 'Fund Managers',
  },
  {
    id: 4,
    name: 'Mr. Taher Badshah',
    title: 'Chief Investment Officer - Equity',
    company: 'Invesco Mutual Fund',
    excerpt: 'Taher has over 30 years of experience in the Indian equity markets. In his role as Chief Investment Officer, Taher is responsible for the equity and fixed income investment function at the firm.',
    date: 'March 25, 2025',
    duration: '8 min',
    image: '/images/interviews/img4.jpg',
    slug: 'taher-badshah',
    category: 'Fund Managers',
  },
  {
    id: 5,
    name: 'Mr. Pankaj Sharma',
    title: 'Head - Equity',
    company: 'DSP Mutual Fund',
    excerpt: 'Pankaj Sharma is the Head of Equity at DSP Mutual Fund. He has over 20 years of experience in the Indian equity markets.',
    date: 'February 10, 2025',
    duration: '18 min',
    image: '/images/interviews/img5.jpg',
    slug: 'pankaj-sharma',
    category: 'Fund Managers',
  },
  {
    id: 6,
    name: 'Ms. Sohini Andani',
    title: 'Fund Manager',
    company: 'SBI Mutual Fund',
    excerpt: 'Sohini Andani is a Fund Manager at SBI Mutual Fund. She manages several equity schemes.',
    date: 'January 15, 2025',
    duration: '14 min',
    image: '/images/interviews/img6.jpg',
    slug: 'sohini-andani',
    category: 'Fund Managers',
  },
  {
    id: 7,
    name: 'Mr. Neelesh Surana',
    title: 'CIO - Equity',
    company: 'Mirae Asset Mutual Fund',
    excerpt: 'Neelesh Surana is the CIO - Equity at Mirae Asset Mutual Fund. He has extensive experience in equity research and fund management.',
    date: 'December 5, 2024',
    duration: '20 min',
    image: '/images/interviews/img7.jpg',
    slug: 'neelesh-surana',
    category: 'Fund Managers',
  },
  {
    id: 8,
    name: 'Mr. Anoop Bhaskar',
    title: 'Head - Equity',
    company: 'IDFC Mutual Fund',
    excerpt: 'Anoop Bhaskar is the Head of Equity at IDFC Mutual Fund. He has over 25 years of experience in the Indian capital markets.',
    date: 'November 20, 2024',
    duration: '16 min',
    image: '/images/interviews/img8.jpg',
    slug: 'anoop-bhaskar',
    category: 'Fund Managers',
  },
  {
    id: 9,
    name: 'Mr. R. Janakiraman',
    title: 'Fund Manager',
    company: 'Franklin Templeton Mutual Fund',
    excerpt: 'R. Janakiraman is a Fund Manager at Franklin Templeton Mutual Fund. He specializes in managing equity portfolios.',
    date: 'October 10, 2024',
    duration: '13 min',
    image: '/images/interviews/img9.jpg',
    slug: 'r-janakiraman',
    category: 'Fund Managers',
  },
  {
    id: 10,
    name: 'Mr. S. Naren',
    title: 'ED & CIO',
    company: 'ICICI Prudential AMC',
    excerpt: 'S. Naren is the Executive Director & Chief Investment Officer at ICICI Prudential AMC. He is known for his value investing approach.',
    date: 'September 1, 2024',
    duration: '22 min',
    image: '/images/interviews/img10.jpg',
    slug: 's-naren',
    category: 'Fund Managers',
  },
  {
    id: 11,
    name: 'Mr. Sankaran Naren',
    title: 'CIO - Equity',
    company: 'Kotak Mutual Fund',
    excerpt: 'Sankaran Naren is the CIO - Equity at Kotak Mutual Fund. He has a wealth of experience in managing diverse equity portfolios.',
    date: 'August 15, 2024',
    duration: '19 min',
    image: '/images/interviews/img11.jpg',
    slug: 'sankaran-naren',
    category: 'Fund Managers',
  },
  {
    id: 12,
    name: 'Mr. Harsha Upadhyaya',
    title: 'CIO - Equity',
    company: 'Kotak Mutual Fund',
    excerpt: 'Harsha Upadhyaya is the CIO - Equity at Kotak Mutual Fund. He is responsible for the overall equity investment strategy.',
    date: 'July 20, 2024',
    duration: '17 min',
    image: '/images/interviews/img12.jpg',
    slug: 'harsha-upadhyaya',
    category: 'Fund Managers',
  },
  {
    id: 13,
    name: 'Mr. G. Pradeep Kumar',
    title: 'CEO',
    company: 'Union AMC',
    excerpt: 'G. Pradeep Kumar is the CEO of Union AMC. He has a strong background in financial services and asset management.',
    date: 'June 5, 2024',
    duration: '25 min',
    image: '/images/interviews/img13.jpg',
    slug: 'g-pradeep-kumar',
    category: 'CEOs',
  },
  {
    id: 14,
    name: 'Mr. Ashish Somaiyaa',
    title: 'CEO',
    company: 'WhiteOak Capital AMC',
    excerpt: 'Ashish Somaiyaa is the CEO of WhiteOak Capital AMC. He has held leadership positions in various asset management companies.',
    date: 'May 1, 2024',
    duration: '21 min',
    image: '/images/interviews/img14.jpg',
    slug: 'ashish-somaiyaa',
    category: 'CEOs',
  },
];

export const featuredInterviewData = {
  title: 'Market Outlook 2025: Expert Predictions',
  description: 'Join our panel of experts as they discuss market trends, investment opportunities, and economic forecasts for the upcoming year.',
  duration: '45 min',
  panel: 'Panel Discussion',
  image: '/images/interviews/img1.jpg',
  slug: 'market-outlook-2025',
};


